export const Config = {
  port: Number(process.env.PORT) || 3333,
}

export const EtapasFunilDefault = [
  { nome: 'Mapeamento', ordem: 1 },
  { nome: 'Entrada de Contato', ordem: 2 },
  { nome: 'Diagnóstico', ordem: 3 },
  { nome: 'Proposta', ordem: 4 },
  { nome: 'Negociação', ordem: 5 },
  { nome: 'Pós Venda', ordem: 6 },
]

export const ErrorMessages = {
  invalidLeadId: 'ID do lead inválido',
  leadNotFound: 'Lead não encontrado',
  invalidUsuarioId: 'ID do usuário responsável inválido',
  usuarioNotFound: 'Usuário responsável não encontrado',
  responsaveisRequired: 'Pelo menos um responsável deve ser informado',
  responsaveisNotFound: 'Um ou mais responsáveis informados não foram encontrados',
  nomeRequired: 'Nome é obrigatório',
  dataCadastroRequired: 'Data de cadastro é obrigatória',
  invalidDataCadastro: 'Data de cadastro inválida',
  invalidDataInicio: 'Data de inicio inválida',
  invalidDataFim: 'Data de fim inválida',
  invalidDataRange: 'Intervalo de datas inválido',
  emailRequired: 'Email é obrigatório',
  senhaRequired: 'Senha é obrigatória',
  invalidCredentials: 'Email ou senha inválidos',
  leadHasNegocios: 'Lead possui negocios vinculadas',
  invalidNegocioId: 'ID da negocio inválido',
  negocioNotFound: 'Negocio não encontrada',
  tituloRequired: 'Título é obrigatório',
  invalidLeadIdRef: 'Lead vinculado inválido',
  leadRefNotFound: 'Lead vinculado não encontrado',
  invalidEtapaFunilId: 'Etapa do funil inválida',
  etapaFunilNotFound: 'Etapa do funil não encontrada',
  invalidValorEstimado: 'Valor estimado inválido',
  invalidPrioridade: 'Prioridade inválida',
  invalidUsuarioIdParam: 'ID do usuário inválido',
  usuarioNotFound: 'Usuário não encontrado',
  usuarioNomeRequired: 'Nome é obrigatório',
  usuarioCargoRequired: 'Cargo é obrigatório',
  usuarioEmailRequired: 'Email é obrigatório',
  usuarioEmailInUse: 'Email já cadastrado',
  usuarioSenhaRequired: 'Senha é obrigatória',
  usuarioHasLeads: 'Usuário possui leads vinculados',
  usuarioHasNegocios: 'Usuário possui negocios vinculadas',
  invalidPerfilAcesso: 'Perfil de acesso inválido',
  relatorioDataInicioRequired: 'Data inicial é obrigatória',
  relatorioDataFimRequired: 'Data final é obrigatória',
  relatorioDatasInvalidas: 'Datas do relatório inválidas',
  relatorioPeriodoInvalido: 'Data inicial não pode ser maior que a data final',
  importFileRequired: 'Arquivo da planilha é obrigatório',
  importFileInvalid: 'Formato inválido. Use .xlsx, .xls ou .csv',
  importSheetEmpty: 'Planilha vazia ou sem cabeçalho',
  importColumnNomeRequired: 'Coluna "nome" é obrigatória na planilha',
  importRuleInvalid: 'Regra de importação inválida',
  invalidInteracaoId: 'ID da interação inválido',
  interacaoNotFound: 'Interação não encontrada',
  interacaoTipoRequired: 'Tipo da interação é obrigatório',
  interacaoTipoInvalid: 'Tipo da interação inválido',
  interacaoDescricaoRequired: 'Descrição é obrigatória',
  interacaoDataRequired: 'Data da interação é obrigatória',
  interacaoDataInvalid: 'Data da interação inválida',
  interacaoNegocioInvalid: 'Negocio vinculada inválida',
  interacaoNegocioNotFound: 'Negocio vinculada não encontrada',
  interacaoNegocioLeadMismatch: 'Negocio não pertence a este lead',
  invalidMotivoPerdaId: 'ID do motivo de perda inválido',
  motivoPerdaNotFound: 'Motivo de perda não encontrado',
  motivoPerdaNomeRequired: 'Nome do motivo é obrigatório',
  motivoPerdaNomeInUse: 'Motivo de perda já cadastrado',
  motivoPerdaInUse: 'Motivo vinculado a negocios e não pode ser excluído',
  motivoPerdaRequired: 'Motivo de perda é obrigatório',
  invalidCargoId: 'ID do cargo inválido',
  cargoNotFound: 'Cargo não encontrado ou inativo',
  cargoNomeRequired: 'Nome do cargo é obrigatório',
  cargoNomeInUse: 'Cargo já cadastrado',
  cargoInUse: 'Cargo vinculado a usuários e não pode ser excluído',
  negocioJaPerdida: 'Negocio já está marcada como perdida',
  etapaPerdidaNotFound: 'Etapa "Perdida" não configurada no funil',
  invalidTarefaId: 'ID da tarefa inválido',
  tarefaNotFound: 'Tarefa não encontrada',
  tarefaTituloRequired: 'Título da tarefa é obrigatório',
  tarefaDataPrazoRequired: 'Data de prazo é obrigatória',
  tarefaDataPrazoInvalid: 'Data de prazo inválida',
  tarefaStatusInvalid: 'Status da tarefa inválido',
  tarefaNegocioInvalid: 'Negocio vinculada inválida',
  tarefaNegocioNotFound: 'Negocio vinculada não encontrada',
  tarefaNegocioLeadMismatch: 'Negocio não pertence a este lead',
  invalidPropostaId: 'ID da proposta inválido',
  propostaNotFound: 'Proposta não encontrada',
  propostaTituloRequired: 'Título da proposta é obrigatório',
  propostaValorInvalid: 'Valor da proposta inválido',
  propostaStatusInvalid: 'Status da proposta inválido',
  propostaDataRequired: 'Data da proposta é obrigatória',
  propostaDataInvalid: 'Data da proposta inválida',
  accessDenied: 'Acesso negado',
}
